#Task: print ბრძანება 40-ჯერ გამოიყენეთ და დაბეჭდეთ თქვენთვის სასურველი ინფორმაიცია
print("Hello, ")
print("today ")
print("I'am ")
print("gonna ")
print("Use ")
print("Print() ")
print("instruction ")
print("40 times, ")
print("Lets start: ")
print("one sheep")
print("two sheep")
print("three sheep")
print("four sheep")
print("five sheep")
print("six sheep")
print("seven sheep")
print("eight sheep")
print("nine sheep")
print("ten sheep")
print("eleven sheep")
print("twelve sheep")
print("thirteen sheep")
print("fourteen sheep")
print("fifteen sheep")
print("sixteen sheep")
print("seventeen sheep")
print("eighteen sheep")
print("ninteen sheep")
print("twenty sheep")
print("twenty-one sheep")
print("twenty-two sheep")
print("twenty-three sheep")
print("twnety-four sheep")
print("twenty-five sheep")
print("twenty-six sheep")
print("twenty-seven sheep")
print("twenty-eight sheep")
print("tw_ z z z z z z ")
print("z z z z z z z z z z z z z z z z z z z z ...")   


